destination: _site
baseurl: "//revstudio.pl/beta/"
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - resources
  - campton
  - build.sh
collections:
  assets:
    permalink: /assets/:path/

# Add collections if needed, i.e.
#   products:
#     output: true
#     permalink: /products/:path/
